server:
  port: 8081
spring:
  application:
    name: ArticlesAPI
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/articles_api_db}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml

security:
  jwt:
    secret-key:
      539EB8387CBA4485FF15D26D190461C1B7A63B3595449024C601E89DD6CD14A6